-- ========================================
-- WARGA PINTAR — FULL SCHEMA V1
-- Run this in Supabase SQL Editor
-- Covers: News, Fees (Iuran), Payments, Reports, Panic Button
-- ========================================

-- 1. NEWS / ANNOUNCEMENTS
CREATE TABLE public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'PENGUMUMAN', -- PENGUMUMAN, KEGIATAN, DARURAT
  author_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_published BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- Everyone can read published news
CREATE POLICY "Public can view published news"
  ON public.news FOR SELECT
  USING (is_published = true);

-- Only Admin can insert/update/delete news
CREATE POLICY "Admins can manage news"
  ON public.news FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );


-- 2. FEES (MASTER IURAN)
CREATE TABLE public.fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, -- e.g. "Iuran Kebersihan & Keamanan"
  amount NUMERIC NOT NULL DEFAULT 0,
  due_date_day INT DEFAULT 10, -- day of month, e.g. 10th
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;

-- Everyone can read active fees
CREATE POLICY "Public can view fees"
  ON public.fees FOR SELECT
  USING (is_active = true);

-- Only Admin can manage fees
CREATE POLICY "Admins can manage fees"
  ON public.fees FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );


-- 3. PAYMENTS (TRANSACTIONS)
CREATE TABLE public.payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  fee_id BIGINT REFERENCES public.fees(id),
  amount NUMERIC NOT NULL,
  period DATE NOT NULL, -- "2026-02-01" for Feb 2026
  status TEXT DEFAULT 'pending', -- pending, paid, overdue
  payment_method TEXT, -- transfer, ewallet, cash
  paid_at TIMESTAMPTZ,
  proof_url TEXT, -- URL to payment proof image
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Users can view their own payments
CREATE POLICY "Users can view own payments"
  ON public.payments FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert payments (upload proof)
CREATE POLICY "Users can create payments"
  ON public.payments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admins can view/update all payments
CREATE POLICY "Admins can manage payments"
  ON public.payments FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );


-- 4. REPORTS (LAPORAN)
CREATE TABLE public.reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL, -- Fasilitas, Kebersihan, Keamanan, Lainnya
  status TEXT DEFAULT 'Menunggu', -- Menunggu, Diproses, Selesai, Ditolak
  image_url TEXT, -- specific bucket path
  location TEXT, -- simple text for now
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Users can view their own reports
CREATE POLICY "Users can view own reports"
  ON public.reports FOR SELECT
  USING (auth.uid() = user_id);

-- Users can create reports
CREATE POLICY "Users can create reports"
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admins/Security can view and update all reports
CREATE POLICY "Staff can manage reports"
  ON public.reports FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'security'))
  );


-- 5. PANIC LOGS (DARURAT)
CREATE TABLE public.panic_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  location TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.panic_logs ENABLE ROW LEVEL SECURITY;

-- Users can insert panic logs
CREATE POLICY "Users can trigger panic"
  ON public.panic_logs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Staff can view/update panic logs
CREATE POLICY "Staff can manage panic logs"
  ON public.panic_logs FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'security'))
  );


-- 6. SEED DATA (OPTIONAL - Run separately if needed)
-- INSERT INTO public.fees (name, amount) VALUES ('Iuran Lingkungan & Keamanan', 150000);
-- INSERT INTO public.news (title, content, category) VALUES ('Kerja Bakti Minggu Ini', 'Akan diadakan kerja bakti membersihkan selokan pada hari Minggu pukul 07:00 WIB.', 'KEGIATAN');
