-- Create the news table
create table public.news (
  id bigint generated by default as identity not null,
  title text not null,
  content text not null,
  category text null default 'PENGUMUMAN'::text,
  author_id uuid null,
  created_at timestamp with time zone null default now(),
  is_published boolean null default true,
  image_url text null, -- Added image_url column as per service implementation plan
  constraint news_pkey primary key (id),
  constraint news_author_id_fkey foreign KEY (author_id) references profiles (id)
) TABLESPACE pg_default;

-- Enable Row Level Security (RLS)
alter table public.news enable row level security;

-- Create policies for access control

-- 1. Allow everyone to read published news
create policy "Enable read access for all users"
on public.news
for select
using (true);

-- 2. Allow authenticated users to insert news (Admin check should be handled in app or separate role table)
-- Assuming any authenticated user can technically insert for now, but frontend restricts it to admins.
-- Ideally, you'd check a role table here, e.g., using (auth.uid() in (select user_id from admin_roles))
create policy "Enable insert for authenticated users only"
on public.news
for insert
with check (auth.role() = 'authenticated');

-- 3. Allow users to update their own news is standard, but for admin panel, we want admins to update any news.
-- Since we don't have a strict admin role in RLS yet, we'll allow authenticated users to update.
create policy "Enable update for authenticated users only"
on public.news
for update
using (auth.role() = 'authenticated');

-- 4. Allow users to delete their own news or admins generally.
create policy "Enable delete for authenticated users only"
on public.news
for delete
using (auth.role() = 'authenticated');

-- Create storage bucket for news images
insert into storage.buckets (id, name, public) values ('news', 'news', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Give public access to news images"
on storage.objects for select
using ( bucket_id = 'news' );

create policy "Allow authenticated users to upload news images"
on storage.objects for insert
with check ( bucket_id = 'news' and auth.role() = 'authenticated' );

create policy "Allow authenticated users to update news images"
on storage.objects for update
with check ( bucket_id = 'news' and auth.role() = 'authenticated' );

create policy "Allow authenticated users to delete news images"
on storage.objects for delete
using ( bucket_id = 'news' and auth.role() = 'authenticated' );
