import { StyleSheet } from 'react-native';
import { Colors } from '../../../constants/Colors';

export const CreateReportStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.green1,
    },
    content: {
        padding: 20,
    },
    formCard: {
        backgroundColor: Colors.white,
        padding: 24,
        borderRadius: 24,
        marginBottom: 25,
        borderWidth: 1,
        borderColor: Colors.green2,
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        color: Colors.green5,
        marginBottom: 8,
        fontWeight: '600',
        paddingLeft: 4,
    },
    input: {
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 15,
        color: Colors.green5,
        backgroundColor: '#FAFAFA',
    },
    dropdownButton: {
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FAFAFA',
    },
    dropdownList: {
        marginTop: 8,
        backgroundColor: Colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colors.green2,
        overflow: 'hidden',
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dropdownText: {
        fontSize: 14,
        color: Colors.green5,
    },
    textArea: {
        minHeight: 120,
    },
    uploadArea: {
        borderWidth: 1,
        borderColor: Colors.green3,
        borderStyle: 'dashed',
        borderRadius: 12,
        height: 120,
        backgroundColor: '#F1F8E9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    uploadText: {
        marginTop: 8,
        fontSize: 13,
        color: Colors.green4,
    },

    // Photo Action Buttons
    photoActionRow: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 4,
    },
    photoButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1.5,
        gap: 8,
    },
    galleryButton: {
        backgroundColor: '#F1F8E9',
        borderColor: Colors.green3,
    },
    cameraButton: {
        backgroundColor: '#E8F5E9',
        borderColor: Colors.green4,
    },
    photoButtonText: {
        fontSize: 13,
        fontWeight: '700',
        color: Colors.green5,
    },
    imagePreviewContainer: {
        position: 'relative',
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
        marginTop: 12,
    },
    removeImageBtn: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
});
