import { StyleSheet, Platform, Dimensions } from 'react-native';
import { ThemeColors } from '../../theme/AppTheme';

const { width } = Dimensions.get('window');

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContent: {
        paddingBottom: 100,
    },
    reporterCard: {
        backgroundColor: colors.surface,
        padding: 16,
        marginBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    reporterInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reporterAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        marginRight: 12,
    },
    avatarPlaceholder: {
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    reporterName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    reporterAddress: {
        fontSize: 13,
        color: colors.textSecondary,
        marginTop: 2,
    },
    contentCard: {
        backgroundColor: colors.surface,
        padding: 16,
        marginBottom: 12,
    },
    contentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    categoryBadge: {
        backgroundColor: colors.primarySubtle,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    categoryText: {
        fontSize: 12,
        color: colors.primary,
        fontWeight: '700',
    },
    timestamp: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    reportTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.textPrimary,
        marginBottom: 8,
    },
    reportDesc: {
        fontSize: 15,
        color: colors.textSecondary,
        lineHeight: 22,
        marginBottom: 16,
    },
    imageWrapper: {
        width: '100%',
        height: 220,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 16,
        backgroundColor: colors.surfaceSubtle,
    },
    reportImage: {
        width: '100%',
        height: '100%',
    },
    zoomIcon: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    locationBox: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: colors.primarySubtle,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    locationText: {
        flex: 1,
        fontSize: 13,
        color: colors.primary,
        fontWeight: '600',
        marginHorizontal: 8,
    },
    timelineCard: {
        backgroundColor: colors.surface,
        padding: 16,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.textPrimary,
        marginBottom: 20,
    },
    timeline: {
        paddingLeft: 8,
    },
    timelineItem: {
        flexDirection: 'row',
        marginBottom: 24,
    },
    timelineIconBox: {
        width: 24,
        alignItems: 'center',
    },
    timelineDot: {
        width: 20,
        height: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    dotActive: {
        backgroundColor: colors.primary,
    },
    dotInactive: {
        backgroundColor: colors.border,
    },
    dotDanger: {
        backgroundColor: colors.danger,
    },
    timelineLine: {
        position: 'absolute',
        top: 20,
        width: 2,
        bottom: -24,
        backgroundColor: colors.border,
        zIndex: 1,
    },
    lineActive: {
        backgroundColor: colors.primary,
    },
    timelineContent: {
        flex: 1,
        marginLeft: 16,
    },
    timelineLabel: {
        flex: 1,
        fontSize: 15,
        fontWeight: 'bold',
        color: colors.textPrimary,
        marginRight: 8,
    },
    timelineSublabel: {
        fontSize: 13,
        color: colors.textSecondary,
        marginTop: 4,
    },
    textInactive: {
        color: colors.textSecondary,
    },
    proofBox: {
        marginTop: 12,
        width: 120,
        height: 120,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.border,
    },
    proofImage: {
        width: '100%',
        height: '100%',
    },
    proofBadge: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.6)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        gap: 4,
    },
    proofText: {
        color: 'white',
        fontSize: 9,
        fontWeight: 'bold',
    },
    actionBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: colors.surface,
        flexDirection: 'row',
        padding: 16,
        paddingBottom: Platform.OS === 'ios' ? 32 : 16,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        gap: 12,
    },
    mainBtn: {
        flex: 2,
        height: 52,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    rejectBtn: {
        flex: 1,
        height: 52,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: colors.danger,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    btnLabel: {
        color: colors.textWhite,
        fontSize: 15,
        fontWeight: 'bold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        padding: 24,
    },
    modalContent: {
        backgroundColor: colors.surface,
        borderRadius: 24,
        padding: 24,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.textPrimary,
        marginBottom: 8,
    },
    modalSubtitle: {
        fontSize: 14,
        color: colors.textSecondary,
        marginBottom: 20,
    },
    modalInput: {
        backgroundColor: colors.surfaceSubtle,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        padding: 12,
        fontSize: 14,
        color: colors.textPrimary,
        textAlignVertical: 'top',
        marginBottom: 20,
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    modalBtn: {
        flex: 1,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnCancel: {
        backgroundColor: colors.surfaceSubtle,
    },
    modalBtnConfirm: {
        backgroundColor: colors.danger,
    },
    modalBtnText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.textSecondary,
    },
    pickImageBtn: {
        height: 150,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: colors.primary,
        borderStyle: 'dashed',
        backgroundColor: colors.primarySubtle,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    pickImageText: {
        marginTop: 8,
        color: colors.primary,
        fontWeight: 'bold',
    },
    imagePreviewBox: {
        height: 200,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 20,
    },
    imagePreview: {
        width: '100%',
        height: '100%',
    },
    removeImageBtn: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    // Image Viewer Styles
    imageViewerOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageViewerContent: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    fullImage: {
        width: width,
        height: width * 1.5,
        maxHeight: '80%',
    },
    closeImageBtn: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 60 : 40,
        right: 20,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
});
