import { StyleSheet, Platform, Dimensions } from 'react-native';
// Version: 1.0.1 - Force refresh for IDE
import { Colors } from '../../constants/Colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    scrollContent: {
        paddingBottom: 100,
    },
    reporterCard: {
        backgroundColor: '#FFF',
        padding: 16,
        marginBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    reporterInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reporterAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        marginRight: 12,
    },
    avatarPlaceholder: {
        backgroundColor: Colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    reporterName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    reporterAddress: {
        fontSize: 13,
        color: '#666',
        marginTop: 2,
    },
    contentCard: {
        backgroundColor: '#FFF',
        padding: 16,
        marginBottom: 12,
    },
    contentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    categoryBadge: {
        backgroundColor: '#E8EAF6',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    categoryText: {
        fontSize: 12,
        color: '#3F51B5',
        fontWeight: '700',
    },
    timestamp: {
        fontSize: 12,
        color: '#999',
    },
    reportTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1A1A1A',
        marginBottom: 8,
    },
    reportDesc: {
        fontSize: 15,
        color: '#444',
        lineHeight: 22,
        marginBottom: 16,
    },
    imageWrapper: {
        width: '100%',
        height: 220,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 16,
        backgroundColor: '#F0F0F0',
    },
    reportImage: {
        width: '100%',
        height: '100%',
    },
    zoomIcon: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    locationBox: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F0F7FF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#D0E4FF',
    },
    locationText: {
        flex: 1,
        fontSize: 13,
        color: Colors.primary,
        fontWeight: '600',
        marginHorizontal: 8,
    },
    timelineCard: {
        backgroundColor: '#FFF',
        padding: 16,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 20,
    },
    timeline: {
        paddingLeft: 8,
    },
    timelineItem: {
        flexDirection: 'row',
        marginBottom: 24,
    },
    timelineIconBox: {
        width: 24,
        alignItems: 'center',
    },
    timelineDot: {
        width: 20,
        height: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    dotActive: {
        backgroundColor: Colors.primary,
    },
    dotInactive: {
        backgroundColor: '#E5E7EB',
    },
    dotDanger: {
        backgroundColor: Colors.danger,
    },
    timelineLine: {
        position: 'absolute',
        top: 20,
        width: 2,
        bottom: -24,
        backgroundColor: '#E5E7EB',
        zIndex: 1,
    },
    lineActive: {
        backgroundColor: Colors.primary,
    },
    timelineContent: {
        flex: 1,
        marginLeft: 16,
    },
    timelineLabel: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#333',
    },
    timelineSublabel: {
        fontSize: 13,
        color: '#666',
        marginTop: 4,
    },
    textInactive: {
        color: '#9CA3AF',
    },
    proofBox: {
        marginTop: 12,
        width: 120,
        height: 120,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#EEE',
    },
    proofImage: {
        width: '100%',
        height: '100%',
    },
    proofBadge: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.6)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        gap: 4,
    },
    proofText: {
        color: 'white',
        fontSize: 9,
        fontWeight: 'bold',
    },
    actionBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        flexDirection: 'row',
        padding: 16,
        paddingBottom: Platform.OS === 'ios' ? 32 : 16,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
        gap: 12,
    },
    mainBtn: {
        flex: 2,
        height: 52,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    rejectBtn: {
        flex: 1,
        height: 52,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: Colors.danger,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    btnLabel: {
        color: 'white',
        fontSize: 15,
        fontWeight: 'bold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        padding: 24,
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 24,
        padding: 24,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: 20,
    },
    modalInput: {
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        padding: 12,
        fontSize: 14,
        textAlignVertical: 'top',
        marginBottom: 20,
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    modalBtn: {
        flex: 1,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnCancel: {
        backgroundColor: '#F3F4F6',
    },
    modalBtnConfirm: {
        backgroundColor: Colors.danger,
    },
    modalBtnText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#666',
    },
    pickImageBtn: {
        height: 150,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: Colors.primary,
        borderStyle: 'dashed',
        backgroundColor: '#F0F7FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    pickImageText: {
        marginTop: 8,
        color: Colors.primary,
        fontWeight: 'bold',
    },
    imagePreviewBox: {
        height: 200,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 20,
    },
    imagePreview: {
        width: '100%',
        height: '100%',
    },
    removeImageBtn: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
});
